---
title: philosophy
output: html_document
runtime: shiny
---
# Filozofia statystyki {#philosophy}

Miałam wątpliwości, czy ten rozdział powinien znaleźć się w tym miejscu, więc nie krępujcie się ominąć go teraz i wrócić w dowolnym innym momencie.

Filozofia jest absolutnie podstawowym, bazowym zagadnieniem, bez którego na ogół doskonale sobie radzimy. Z jednej więc strony czuję, że lepiej na samym początku podać założenia, na których wszystko się opiera, z drugiej - nie trzeba rozumieć działania silnika, żeby prowadzić samochód. A czytelnik, który potrzebuje już teraz dojeżdżać na studia lub do pracy, może zniechęcić się na tym etapie i uznać, że nie tego szukał.

Podsumowując: zapraszam do wgryzienia się w konkretną statystykę w kolejnych rozdziałach i wrócenia do tego w dogodnym momencie.


Wśród matematyków nie ma pełnej zgodności co do tego, na jakiej zasadzie istnieje matematyka. Nieco upraszczając, można ich podzielić na dwa przeciwstawne obozy:

I - Ci, którzy uważają ją za faktyczną właściwością świata rzeczywistego. Sądzą oni, że świat "działa" według wzorów matematycznych. Można nawet spotkać się z określeniami, że matematyka jest językiem Boga lub językiem Natury - a więc że była wzorcem, według którego wszystko powstało.

II - Ci, dla których jest ludzkim wynalazkiem, formalnym językiem opisu świata. Trójkąty i kwadraty nie istnieją tak, jak gwiazdy czy drzewa. Są abstrakcyjnymi pojęciami, które pomagają nam radzić sobie ze złożonością świata, ponieważ jeśli udowodnimy coś dla tych uproszczonych, ogólnych obiektów, możemy to - z pewną utratą dokładności - zastosować do rzeczywistych obiektów.

Według pierwszej grupy obiekty rzeczywiste są realizacjami bardziej abstrakcyjnych obiektów matematycznych, według drugiej obiekty matematyczne to uogólnienia powstałe na podstawie obserwacji rzeczywistych obiektów. Mimo przeciwstawnych poglądów, matematyka nie ma raczej problemów ze spójnością. Największym wyzwaniem praktycznym jest chyba to, czy poprawnie będzie powiedzieć, że Pitagoras odkrył swoje twierdzenie o trójkącie prostokątnym, czy raczej że je wymyślił.

Według pierwszej grupy obiekty rzeczywiste są realizacjami bardziej abstrakcyjnych obiektów matematycznych, według drugiej obiekty matematyczne to uogólnienia powstałe na podstawie obserwacji rzeczywistych obiektów. Mimo takich przeciwstawnych poglądów, matematyka nie ma raczej problemów ze spójnością. Największym problemem praktycznym jest chyba stwierdzenie, czy poprawnie będzie powiedzieć, że Pitagoras odkrył swoje twierdzenie o trójkącie prostokątnym, czy raczej że je wymyślił.

Jeśli jednak chcemy wyrobić sobie statystyczną intuicję, możemy już poczuć różnicę. W fizyce, gdzie odchyłki przewidywań modelu od empirycznych danych są niewielkie, i zwykle można je złożyć na karb zaokrągleń albo błędów pomiarowych, może się wydawać, że te planety czy gwiazdy faktycznie poruszają się po trajektoriach wyznaczanych przez równania fizyczne - prawa natury. W ekonomii czy socjologii błędy są zbyt duże, by uważać, że naprawdę znamy formułę, która kreuje empiryczne wartości. Modele postrzega się jako uproszczone schematy, możliwie dobrze dopasowane do rzeczywistości. 

Ale technicznie rzecz biorąc, modele te powstają tak samo - przez taki dobór równania, żeby przy podstawieniu rzeczywistych wartości, dawało wyniki podobne do rzeczywistych.

W poniższym programie wygenerowano 100 losowych liczb z zakresu od 0 do 1 (to będą wartości x) oraz 100 liczb z rozkładu normalnego o średniej 0 i wybranym odchyleniu standardowym (to losowe błędy). O tym, czym jest odchylenie standardowe, dowiecie się w następnym rozdziale - na razie niech wystarczy nam, że im jest większe, tym bardziej oddalone od zera mogą być wielkości błędów. 
Wartości y obliczymy jako: $$\ y = 3.67x + 0.82$$ i do każdej dodamy wylosowany błąd.

Następnie na podstawie pewnej liczby losowo wybranych punktów spróbujemy dopasować liniowe równanie.

<!-- include_app -->

Łatwo zauważyć, że im większa próba i im mniejsze odchylenie błędów, tym bardziej dopasowane równanie przypomina równanie oryginalne.

Jeśli zgadzamy się z poglądami Grupy I, to dane zebrane w rzeczywistym świecie są jak punkty na wykresie: wiemy, że zostały wygenerowane przez jakieś równanie, i wierzymy, że możemy to równanie odkryć. Jeśli uda się udoskonalić pomiar tak, że błąd będzie niezauważalny, lub zebrać tyle danych, że uśredni się niemal do zera, to poznamy oryginalne równanie - prawo natury, które tworzy punkty.

Z kolei dla Grupy II to stwierdzenie jest nieco naiwne. W świecie rzeczywistym - a nie symulacji, jak tutaj - nie mamy dostępu ani do oryginalnego równania, ani do wszystkich istniejących punktów. Równanie, które dopasowaliśmy, może być użyteczne, ale nie można zakładać, że nie jest uproszczeniem. Na rzeczywiste wartości może mieć wpływ dodatkowa zmienna z, której nawet nie wzięliśmy pod uwagę. W innych warunkach punkty mogą zachowywać się inaczej. To, co wygląda na elegancką prostą, może być tak naprawdę wycinkiem wielkiej paraboli.

W tej książce przyjęte jest podejście drugie. Zakładam, że matematyka jest tylko językiem do opisu rzeczywistości. Jak każdy język, zawsze upraszacza opisywany świat, a przez to zawsze przedstawia go błędnie. Dobrze to podsumowuje cytat statystyka **George'a Boxa**:

> Wszystkie modele są błędne, ale niektóre są użyteczne.

