--- 
title: "Think Inside The Box"
author: "Agnieszka Choczyńska"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: agachocz/inside-the-box
description: "Interaktywny podręcznik statystyki"
---

# Wstęp

W powszechnym przekonaniu utarło się, że wyobraźnia i matematyka nie mają ze sobą nic wspólnego. Gorzej nawet: że sucha, bezduszna matematyka zabija w ludziach kreatywność i twórcze zdolności. Podzielono świat na ścisłowców i humanistów, w czasopismach można znaleźć barwne infografiki o przeciwstawnych półkulach mózgu, a autorzy książek popularnonaukowych przez dwie strony przepraszają i uspokajają czytelników, ilekroć potrzebują przytoczyć jakiś wzór.

A jednak tym, co przeszkadzało mi na większości matematycznych przedmiotów podczas pięciu lat studiów był właśnie brak wyobraźni. Można stosować wzory i wyciągać wnioski według wyuczonych reguł, ale znacznie trudniej wyrobić sobie intuicję, jak - dla przykładu - niespełnienie założenia o normalności rozkładu może wpłynąć na wnioskowanie statystyczne.

Dlatego ten podręcznik stawia sobie za cel rozwijanie właśnie intuicji statystycznej. Daje możliwość zobaczenia, jak zachowują się rozkłady zmiennych czy statystyk przy różnych parametrach, i co z tego wynika.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
